import CryptoKit
import Foundation
import Synchronization
import Testing

@testable import TodexCore

// Shared vectors: Fixtures/transport-v2.json is a verbatim copy of
// TodeX_protocol/tests/fixtures/transport-v2.json (generated by its
// scripts/generate-transport-v2-vectors.cjs). Re-copy it whenever the
// generator changes; `vectorFileMatchesProtocolCheckout` flags drift when the
// sibling checkout is present.
struct TransportV2Tests {
    // MARK: Vectors

    @Test(arguments: ["x25519", "ml-kem-768"])
    func keyScheduleAndWebSocketFramesMatchVectors(_ name: String) throws {
        let v = try protocolVector(name)
        let ws = v["ws"]
        let serverPublic = try hex(v["server"]["publicKey"])
        let handshake = try clientHandshake(v, ws)
        #expect(handshake.clientMaterial == (try hex(ws["clientMaterial"])))
        #expect(handshake.shared.bytes == (try hex(ws["shared"])))
        let serverNonce = try TransportWebSocketHandshake.parseHello(ws["hello"].stringValue)
        #expect(serverNonce == (try hex(ws["serverNonce"])))
        let keys = TransportKeySchedule.derive(
            label: ws["label"].stringValue, deviceID: ws["deviceId"].stringValue, serverStaticPublic: serverPublic,
            handshake: handshake, clientNonce: try hex(ws["clientNonce"]), serverNonce: serverNonce)
        #expect(keys.th == (try hex(ws["th"])))
        #expect(keys.kUp.bytes == (try hex(ws["kUp"])))
        #expect(keys.kDown.bytes == (try hex(ws["kDown"])))

        let client = try TransportWebSocketHandshake(
            serverPublicKey: serverPublic, deviceID: ws["deviceId"].stringValue, handshake: handshake,
            clientNonce: try hex(ws["clientNonce"]))
        #expect(client.queryParameters == ws["query"].objectValue.mapValues(\.stringValue))
        let channel = try client.acceptHello(ws["hello"].stringValue)
        #expect(throws: TransportCryptoError.self) { try client.acceptHello(ws["hello"].stringValue) }
        for frame in ws["frames"].arrayValue {
            if frame["direction"] == "up" {
                #expect(try channel.seal(frame["plaintext"].stringValue) == (try hex(frame["frame"])))
            } else {
                #expect(try channel.open(hex(frame["frame"])) == frame["plaintext"].stringValue)
            }
        }
    }

    @Test(arguments: ["x25519", "ml-kem-768"])
    func restRequestAndResponseMatchVectors(_ name: String) throws {
        let v = try protocolVector(name)
        let rest = v["rest"]
        let serverPublic = try hex(v["server"]["publicKey"])
        let handshake = try clientHandshake(v, rest)
        let clientNonce = try hex(rest["clientNonce"])
        let keys = TransportKeySchedule.derive(
            label: TransportV2.restLabel, deviceID: "", serverStaticPublic: serverPublic, handshake: handshake,
            clientNonce: clientNonce, serverNonce: Data())
        #expect(keys.th == (try hex(rest["th"])))
        #expect(keys.kUp.bytes == (try hex(rest["kUp"])))
        #expect(keys.kDown.bytes == (try hex(rest["kDown"])))

        // Clarification 5: seal the vector plaintext, never a re-serialization.
        let requestPlaintext = try hex(rest["request"]["plaintext"])
        let up = TransportRecordCipher(key: keys.kUp, th: keys.th, direction: TransportV2.directionUp)
        #expect(try TransportRecordStream.seal(requestPlaintext, cipher: up) == (try hex(rest["request"]["stream"])))
        let inner = try TransportInnerRequest.decode(requestPlaintext)
        #expect(inner.method == "POST" && inner.path == "/v2/workspaces" && inner.query == "source=vector")
        #expect(inner.headers["x-todex-device-id"] == "dev_LobItzFYN8xbKubO")
        #expect(inner.body == (try hex(rest["request"]["body"])))

        // Outer headers are byte-exact; our own body must open on the server side.
        let sealed = try TransportRestTunnel.seal(
            inner, serverPublicKey: serverPublic, handshake: handshake, clientNonce: clientNonce)
        #expect(sealed.headers == rest["outerHeaders"].objectValue.mapValues(\.stringValue))
        let serverUp = TransportRecordCipher(key: keys.kUp, th: keys.th, direction: TransportV2.directionUp)
        #expect(try TransportInnerRequest.decode(TransportRecordStream.open(sealed.body, cipher: serverUp)) == inner)

        let response = try TransportRestTunnel.openResponse(
            hex(rest["response"]["stream"]), cipher: sealed.responseCipher)
        #expect(response.status == 201)
        #expect(response.headers == ["content-type": "application/json"])
        #expect(response.body == (try hex(rest["response"]["body"])))
        let down = TransportRecordCipher(key: keys.kDown, th: keys.th, direction: TransportV2.directionDown)
        #expect(
            try TransportRecordStream.seal(hex(rest["response"]["plaintext"]), cipher: down)
                == (try hex(rest["response"]["stream"])))

        // Streaming: byte-at-a-time delivery yields the same head and body.
        let streaming = TransportSealedResponseDecoder(
            cipher: TransportRecordCipher(key: keys.kDown, th: keys.th, direction: TransportV2.directionDown))
        var body = Data()
        for byte in try hex(rest["response"]["stream"]) {
            for part in try streaming.push(Data([byte])) { body += part }
        }
        try streaming.finish()
        #expect(streaming.head == TransportInnerResponseHead(status: 201, headers: ["content-type": "application/json"]))
        #expect(body == (try hex(rest["response"]["body"])))
    }

    @Test(arguments: ["x25519", "ml-kem-768"])
    func multiRecordResponseMatchesDigests(_ name: String) throws {
        let v = try protocolVector(name)
        let rest = v["rest"]
        let multi = rest["multiRecordResponse"]
        let head = Data(multi["headJson"].stringValue.utf8)
        let body = Data((0..<multi["bodyLength"].intValue).map { UInt8($0 % 251) })
        let plaintext = TransportBytes.u32(head.count) + head + body
        #expect(plaintext.count == multi["plaintextLength"].intValue)
        #expect(sha256Hex(plaintext) == multi["plaintextSha256"].stringValue)
        let keys = try restKeys(v)
        let stream = try TransportRecordStream.seal(
            plaintext, cipher: TransportRecordCipher(key: keys.kDown, th: keys.th, direction: TransportV2.directionDown))
        #expect(stream.count == multi["streamLength"].intValue)
        #expect(sha256Hex(stream) == multi["streamSha256"].stringValue)
        var offset = 0
        for record in multi["records"].arrayValue {
            let length = TransportBytes.readU32(stream.dropFirst(offset))
            #expect(length == record["ciphertextLength"].intValue)
            #expect(sha256Hex(stream.subdata(in: offset + 4..<offset + 4 + length)) == record["ciphertextSha256"].stringValue)
            offset += 4 + length
        }
        #expect(offset == stream.count)

        // Streamed open in uneven chunks that straddle record boundaries.
        let decoder = TransportSealedResponseDecoder(
            cipher: TransportRecordCipher(key: keys.kDown, th: keys.th, direction: TransportV2.directionDown))
        var opened = Data()
        var index = 0
        var size = 1
        while index < stream.count {
            let end = min(index + size, stream.count)
            for part in try decoder.push(stream.subdata(in: index..<end)) { opened += part }
            index = end
            size = size * 3 + 7
        }
        try decoder.finish()
        #expect(decoder.head?.status == 200)
        #expect(opened == body)
    }

    @Test(arguments: ["x25519", "ml-kem-768"])
    func everyFailureVectorFails(_ name: String) throws {
        let v = try protocolVector(name)
        let failures = v["failures"].arrayValue
        #expect(failures.count == 13)
        for failure in failures {
            let input = try hex(failure["input"])
            switch failure["kind"].stringValue {
            case "ws":
                let channel = try wsChannel(v)
                #expect(throws: TransportCryptoError.self, "\(failure["name"].stringValue)") { try channel.open(input) }
            case "rest":
                let keys = try restKeys(v)
                let cipher = TransportRecordCipher(key: keys.kDown, th: keys.th, direction: TransportV2.directionDown)
                #expect(throws: TransportCryptoError.self, "\(failure["name"].stringValue)") {
                    try TransportRestTunnel.openResponse(input, cipher: cipher)
                }
                // The streaming decoder rejects it too, however it is chunked.
                let streaming = TransportSealedResponseDecoder(
                    cipher: TransportRecordCipher(key: keys.kDown, th: keys.th, direction: TransportV2.directionDown))
                #expect(throws: TransportCryptoError.self, "\(failure["name"].stringValue) streamed") {
                    for byte in input { _ = try streaming.push(Data([byte])) }
                    try streaming.finish()
                }
            default:
                Issue.record("unknown failure kind \(failure["kind"])")
            }
        }
    }

    @Test func pairingV3MatchesVector() throws {
        let v = try vectors()["pairingV3"]
        let clientKey = try Curve25519.KeyAgreement.PrivateKey(rawRepresentation: hex(v["clientSecretKey"]))
        #expect(clientKey.publicKey.rawRepresentation == (try hex(v["clientPublicKey"])))
        let device = try #require(DeviceIdentity(secretKeyBase64URL: CryptoEncoding.encode(hex(v["deviceSeed"]))))
        #expect(device.publicKey == (try hex(v["devicePublicKey"])))
        let commitment = try DevicePairingV3.commitment(
            clientPublic: clientKey.publicKey.rawRepresentation, clientNonce: hex(v["clientNonce"]))
        #expect(commitment == (try hex(v["commitment"])))
        #expect(CryptoEncoding.encode(commitment) == v["commitmentBase64Url"].stringValue)
        let material = try PairingMaterial(
            v3RequestID: v["requestId"].stringValue, privateKey: clientKey, serverPublicKey: hex(v["serverPublicKey"]),
            device: device, clientNonce: hex(v["clientNonce"]))
        #expect(material.transcript == (try hex(v["transcript"])))
        #expect(Data(SHA256.hash(data: material.transcript)) == (try hex(v["transcriptHash"])))
        #expect(material.verificationCode == v["verificationCode"].stringValue)
        #expect(material.wrapKey.bytes == (try hex(v["wrapKey"])))
        #expect(material.pollProof.bytes == (try hex(v["pollProof"])))
        #expect(material.cancelProof.bytes == (try hex(v["cancelProof"])))
        #expect(throws: TodexError.self) {
            try DevicePairingV3.commitment(clientPublic: clientKey.publicKey.rawRepresentation, clientNonce: Data(count: 16))
        }
    }

    @Test func vectorFileMatchesProtocolCheckout() throws {
        let copy = try #require(Bundle.module.url(forResource: "transport-v2", withExtension: "json", subdirectory: "Fixtures"))
        let source = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
            .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
            .appendingPathComponent("TodeX_protocol/tests/fixtures/transport-v2.json")
        guard FileManager.default.fileExists(atPath: source.path) else { return }
        #expect(try Data(contentsOf: copy) == Data(contentsOf: source), "re-copy transport-v2.json from TodeX_protocol")
    }

    // MARK: Primitive rules

    @Test func recordCountersAreStrictAndExhaustBeforeMax() throws {
        let key = SymmetricKey(size: .bits256)
        let th = Data(repeating: 7, count: 32)
        let sender = TransportRecordCipher(key: key, th: th, direction: 2, counter: UInt64.max - 1)
        let record = try sender.seal(Data("last".utf8), final: false)
        #expect(record.counter == UInt64.max - 1)
        #expect(throws: TransportCryptoError("record counter exhausted")) { try sender.seal(Data(), final: false) }
        let receiver = TransportRecordCipher(key: key, th: th, direction: 2, counter: UInt64.max - 1)
        #expect(throws: TransportCryptoError.self) { try receiver.open(counter: 0, ciphertext: record.ciphertext, final: false) }
        // Wrong final flag fails authentication without advancing the counter.
        #expect(throws: TransportCryptoError.self) {
            try receiver.open(counter: record.counter, ciphertext: record.ciphertext, final: true)
        }
        #expect(try receiver.open(counter: record.counter, ciphertext: record.ciphertext, final: false) == Data("last".utf8))
        receiver.dispose()
        #expect(throws: TransportCryptoError("cipher disposed")) { try receiver.open(counter: 0, ciphertext: Data(count: 16), final: false) }
    }

    @Test func oversizedFrameIsRejectedWithoutConsumingACounter() throws {
        let v = try protocolVector("x25519")
        let channel = try wsChannel(v, maxFrameBytes: 100)
        let limit = TransportSizeCheck.webSocketPlaintextLimit(maxFrameBytes: 100)
        #expect(throws: TransportPayloadTooLargeError(size: limit + 1, limit: limit)) {
            try channel.seal(String(repeating: "x", count: limit + 1))
        }
        // The next frame still uses counter 0, exactly as in the vector.
        let first = v["ws"]["frames"].arrayValue[0]
        #expect(try channel.seal(first["plaintext"].stringValue) == (try hex(first["frame"])))
        #expect(TransportSizeCheck.webSocketPlaintextLimit() == 8 * 1024 * 1024 - 24)
    }

    @Test(arguments: [
        #"{"type":"todex.transport.hello","version":"2","serverNonce":"fReESPjfplv6OMuW5COdyWDH53CdHWt8CcvfRsgNNCo"}"#,
        #"{"type":"todex.transport.hello","version":1,"serverNonce":"fReESPjfplv6OMuW5COdyWDH53CdHWt8CcvfRsgNNCo"}"#,
        #"{"type":"todex.transport.hello","version":true,"serverNonce":"fReESPjfplv6OMuW5COdyWDH53CdHWt8CcvfRsgNNCo"}"#,
        #"{"type":"hello","version":2,"serverNonce":"fReESPjfplv6OMuW5COdyWDH53CdHWt8CcvfRsgNNCo"}"#,
        #"{"type":"todex.transport.hello","version":2,"serverNonce":"fReESPjfplv6OMuW5COdyWDH53CdHWt8CcvfRsgNNC"}"#,
        #"{"type":"todex.transport.hello","version":2,"serverNonce":"fReESPjfplv6OMuW5COdyWDH53CdHWt8CcvfRsgNNCo="}"#,
        #"{"type":"todex.transport.hello","version":2}"#, "not json", "[]",
    ])
    func malformedHellosAreRejected(_ hello: String) {
        #expect(throws: TransportCryptoError.self) { try TransportWebSocketHandshake.parseHello(hello) }
    }

    @Test func helloIgnoresUnknownFields() throws {
        let nonce = try TransportWebSocketHandshake.parseHello(
            #"{"future":[1],"type":"todex.transport.hello","version":2,"serverNonce":"fReESPjfplv6OMuW5COdyWDH53CdHWt8CcvfRsgNNCo"}"#)
        #expect(nonce.count == 32)
    }

    @Test func innerRequestRejectsNestingAndBadPaths() throws {
        for path in ["/v2/sealed", "/v2/sealed/x", "v2/x", "/v2/x?y=1", "/v2/x#f"] {
            #expect(throws: (any Error).self, "\(path)") { try TransportInnerRequest(method: "GET", path: path).encoded() }
        }
        let request = TransportInnerRequest(
            method: "get", path: "/v2/a%2Fb", query: "?q=1", headers: ["Accept": "application/json"], body: Data([1, 2]))
        let decoded = try TransportInnerRequest.decode(request.encoded())
        #expect(decoded.method == "GET" && decoded.query == "q=1" && decoded.headers == ["accept": "application/json"])
        // Empty plaintext still produces one (empty, final) record (Clarification 4).
        let key = SymmetricKey(size: .bits256)
        let stream = try TransportRecordStream.seal(
            Data(), cipher: TransportRecordCipher(key: key, th: Data(count: 32), direction: 1))
        #expect(stream.count == 4 + 16)
        #expect(
            try TransportRecordStream.open(stream, cipher: TransportRecordCipher(key: key, th: Data(count: 32), direction: 1))
                .isEmpty)
    }

    // MARK: Client rules

    @Test func modeFollowsClientRules() {
        let key = CryptoEncoding.encode(Curve25519.KeyAgreement.PrivateKey().publicKey.rawRepresentation)
        func mode(_ url: String, _ encryption: EncryptionProtocol = .none, _ publicKey: String = "") -> SecureTransportMode {
            .resolve(BackendConnection(serverURL: url, encryption: encryption, publicKey: publicKey))
        }
        #expect(mode("https://lan.example:7345", .x25519, key) == .v2(.x25519))
        #expect(mode("http://127.0.0.1:7345", .mlkem768, key) == .v2(.mlkem768))
        #expect(mode("http://192.168.1.2:7345") == .refused)
        #expect(mode("http://192.168.1.2:7345", .x25519, "  ") == .refused)
        for loopback in [
            "http://127.0.0.1:7345", "http://127.9.8.7", "http://localhost:7345", "http://LOCALHOST.", "http://[::1]:7345",
            "http://[::ffff:127.0.0.1]", "http://[::ffff:7f00:1]",
        ] {
            #expect(mode(loopback) == .plaintext, "\(loopback)")
        }
        for remote in ["http://128.0.0.1", "http://127.0.0.1.example.com", "http://[::2]", "http://[::ffff:c0a8:1]", "not a url"] {
            #expect(mode(remote) == .refused, "\(remote)")
        }
        let pinned = BackendConnection(serverURL: "https://lan.example", encryption: .x25519, publicKey: key)
        #expect(throws: Never.self) { try SecureTransportError.checkPolicy(pinned, requiredProtocol: "x25519") }
        #expect(throws: Never.self) { try SecureTransportError.checkPolicy(pinned, requiredProtocol: "none") }
        #expect(throws: TodexError.self) { try SecureTransportError.checkPolicy(pinned, requiredProtocol: "ml-kem-768") }
        #expect(throws: TodexError.self) {
            try SecureTransportError.checkPolicy(BackendConnection(serverURL: "https://lan.example"), requiredProtocol: "none")
        }
    }

    @Test func refusedProfileNeverTouchesTheNetwork() async throws {
        let fixture = NetworkHTTPFixture { _ in .json(["ok": true]) }
        defer { fixture.close() }
        let connection = BackendConnection(serverURL: "https://lan.example:7345")
        let transport = BackendSecureTransport(
            connection: connection, session: fixture.session, makeSocket: { _ in FakeV2Server.unreachable() })
        #expect(transport.mode == .refused)
        await #expect(throws: TodexError.self) { _ = try await transport.request(method: .get, path: "/v2/version") }
        await #expect(throws: TodexError.self) { _ = try await transport.openWebSocket() }
        // Every REST entry point follows the same rules; none falls back to plaintext.
        await #expect(throws: TodexError.self) {
            _ = try await HTTPClient(connection: connection, session: fixture.session).request(path: "/v2/version")
        }
        await #expect(throws: TodexError.self) {
            _ = try await APIClient(connection: connection, session: fixture.session).health()
        }
        #expect(fixture.requests.isEmpty)
        // An unpinned loopback profile stays plaintext.
        _ = try await fixture.client().request(path: "/v2/version")
        #expect(fixture.requests.count == 1 && fixture.requests[0].url?.path == "/v2/version")
    }

    @Test func unusablePinnedKeyIsAConfigurationErrorBeforeSending() async throws {
        let fixture = NetworkHTTPFixture { _ in .json(["ok": true]) }
        defer { fixture.close() }
        for (encryption, key) in [
            (EncryptionProtocol.x25519, CryptoEncoding.encode(Data(count: 32))),
            (.x25519, CryptoEncoding.encode(Data(count: 31))), (.mlkem768, CryptoEncoding.encode(Data(count: 32))),
        ] {
            var connection = fixture.client().connection
            connection.encryption = encryption
            connection.publicKey = key
            let transport = BackendSecureTransport(
                connection: connection, session: fixture.session, makeSocket: { _ in FakeV2Server.unreachable() })
            for method in [HTTPMethod.get, .post] {
                do {
                    _ = try await transport.request(method: method, path: "/v2/x")
                    Issue.record("expected a configuration error")
                } catch TodexError.configuration {}
            }
            await #expect(throws: TodexError.self) { _ = try await transport.openWebSocket() }
        }
        #expect(fixture.requests.isEmpty)
    }

    // MARK: Tunnel end to end (in-memory server)

    @Test(arguments: ["x25519", "ml-kem-768"])
    func restTunnelRoundTripsAndSignsTheInnerRequest(_ name: String) async throws {
        let server = try FakeServerKeys(protocolVector(name))
        let seen = Mutex<[TransportInnerRequest]>([])
        let fixture = NetworkHTTPFixture { request in
            #expect(request.url?.path == "/v2/sealed" && request.httpMethod == "POST")
            #expect(request.url?.query == nil)
            let (inner, down) = try server.openRequest(request)
            seen.withLock { $0.append(inner) }
            return try server.reply(
                TransportInnerResponse(
                    status: inner.path == "/v2/missing" ? 404 : 200, headers: ["Content-Type": "application/json"],
                    body: Data(#"{"echo":\#(String(decoding: inner.body.isEmpty ? Data("null".utf8) : inner.body, as: UTF8.self))}"#.utf8)),
                cipher: down)
        }
        defer { fixture.close() }
        let transport = server.transport(fixture, deviceSecret: "FRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRU")
        #expect(transport.mode == .v2(server.encryption))
        let response = try await transport.request(
            method: .post, path: "/v2/workspaces/\(HTTPClient.segment("a/b"))", query: ["q": "a+b"],
            body: Data(#"{"name":"demo"}"#.utf8))
        #expect(response.status == 200)
        #expect(response.headers["content-type"] == "application/json")
        #expect(try JSONDecoder().decode(JSONValue.self, from: response.body) == ["echo": ["name": "demo"]])
        let inner = try #require(seen.withLock { $0.first })
        #expect(inner.method == "POST" && inner.path == "/v2/workspaces/a%2Fb" && inner.query == "q=a%2Bb")
        #expect(inner.headers["x-todex-device-id"] == "dev_1-HghL4hOwHlBoUq")
        #expect(inner.headers["content-type"] == "application/json" && inner.headers["accept"] == "application/json")
        // The device signature covers the inner method, path, query and body.
        let payload = DeviceIdentity.payload(
            deviceID: "dev_1-HghL4hOwHlBoUq", method: "POST", path: inner.path, canonicalQuery: "q=a%2Bb",
            timestamp: inner.headers["x-todex-auth-ts"]!, nonce: inner.headers["x-todex-auth-nonce"]!, body: inner.body)
        let device = try #require(DeviceIdentity(secretKeyBase64URL: "FRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRU"))
        #expect(
            try Curve25519.Signing.PublicKey(rawRepresentation: device.publicKey)
                .isValidSignature(CryptoEncoding.decode(inner.headers["x-todex-auth-sig"]!), for: payload))
        // Outer requests never carry the inner credential in the clear.
        #expect(fixture.requests.allSatisfy { $0.value(forHTTPHeaderField: "x-todex-device-id") == nil })

        // Inner 404 is authenticated and reported as such.
        let missing = try await transport.request(method: .get, path: "/v2/missing")
        #expect(missing.status == 404)
    }

    @Test func unsealedOrTamperedTunnelResponsesFail() async throws {
        let server = try FakeServerKeys(protocolVector("x25519"))
        let behavior = Mutex("400")
        let fixture = NetworkHTTPFixture { request in
            let (_, down) = try server.openRequest(request)
            switch behavior.withLock({ $0 }) {
            case "400":
                return .json(["error": ["code": "TRANSPORT_CRYPTO_FAILED", "message": "transport crypto failure"]], status: 400)
            case "plain200":
                return .json(["requiredProtocol": "none"])
            default:
                var reply = try server.reply(TransportInnerResponse(status: 200, body: Data("{}".utf8)), cipher: down)
                reply = NetworkHTTPReply(
                    status: 200, data: reply.data.dropLast() + Data([reply.data.last! ^ 1]), headers: reply.headers)
                return reply
            }
        }
        defer { fixture.close() }
        let transport = server.transport(fixture)
        do {
            _ = try await transport.request(method: .get, path: "/v2/version")
            Issue.record("expected an API error")
        } catch TodexError.configuration(let message) {
            // The backend could not open a request sealed to the pinned key: re-pair.
            #expect(message == SecureTransportError.transportRejected.localizedDescription)
        }
        behavior.withLock { $0 = "plain200" }
        await #expect(throws: TransportCryptoError.self) { _ = try await transport.request(method: .get, path: "/v2/version") }
        behavior.withLock { $0 = "tampered" }
        await #expect(throws: TransportCryptoError.self) { _ = try await transport.request(method: .get, path: "/v2/version") }
        // A mutation whose sealed answer fails cannot prove it did not apply.
        await #expect(throws: TodexError.self) {
            do { _ = try await transport.request(method: .post, path: "/v2/x", body: Data("{}".utf8)) } catch {
                guard case TodexError.unknownOutcome = error else { throw TodexError.invalid("expected unknownOutcome") }
                throw error
            }
        }
    }

    // MARK: WebSocket end to end (in-memory server)

    @Test(arguments: ["x25519", "ml-kem-768"])
    func realtimeClientConnectsOverV2AndClosesWith4400OnTamper(_ name: String) async throws {
        let server = try FakeServerKeys(protocolVector(name))
        let fixture = NetworkHTTPFixture { request in
            let (inner, down) = try server.openRequest(request)
            #expect(inner.path == "/v2/transport-policy")
            return try server.reply(
                TransportInnerResponse(
                    status: 200, headers: ["content-type": "application/json"],
                    body: Data(#"{"requiredProtocol":"\#(server.encryption.rawValue)","transportVersion":2}"#.utf8)),
                cipher: down)
        }
        defer { fixture.close() }
        let socket = Mutex<FakeV2Server?>(nil)
        let connection = server.connection(fixture, deviceSecret: "FRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRU")
        let transport = BackendSecureTransport(
            connection: connection, session: fixture.session,
            makeSocket: { request in
                let fake = FakeV2Server(request: request, keys: server)
                socket.withLock { $0 = fake }
                return fake
            })
        let client = RealtimeClient(connection: connection, transport: transport)
        var events = client.events.makeAsyncIterator()
        try await client.connect()
        // Every frame (including ping results) is also emitted; skip to the one of interest.
        func next(_ type: JSONValue) async -> JSONValue? {
            while let event = await events.next() { if event["type"] == type { return event } }
            return nil
        }
        #expect(await next("connection.ready") != nil)
        let fake = try #require(socket.withLock { $0 })
        #expect(fake.query["tv"] == "2" && fake.query["enc"] == server.encryption.rawValue)
        #expect(fake.query["historyEncryption"] == "1" && fake.query["device_id"] == "dev_1-HghL4hOwHlBoUq")
        #expect(fake.deviceID == "dev_1-HghL4hOwHlBoUq")
        _ = try await client.command(type: "server.ping", payload: [:])
        #expect(fake.receivedTypes == ["server.ping", "server.ping"])
        // Concurrent commands reach the wire in counter order: the fake server
        // opens each frame with the next expected counter or fails.
        try await withThrowingTaskGroup(of: JSONValue.self) { group in
            for index in 0..<30 {
                group.addTask {
                    try await client.command(type: "conversation.create", payload: ["index": .number(Double(index))])
                }
            }
            var results: Set<JSONValue> = []
            for try await result in group { results.insert(result["index"]) }
            #expect(results.count == 30)
        }
        #expect(fake.receivedTypes.count == 32)
        #expect(fake.textFramesAfterHello == 0)
        try fake.push(["type": "conversation.event", "payload": ["text": "你好 ✓"]])
        #expect(await next("conversation.event") == ["type": "conversation.event", "payload": ["text": "你好 ✓"]])

        fake.pushTampered(["type": "conversation.event", "payload": [:]])
        let closed = await next("connection.closed")
        #expect(closed?["payload"]["retryable"] == true)
        #expect(fake.closeCode == TransportV2.wsCloseCode && fake.closeReason == TransportV2.wsCloseReason)
    }

    @Test func socketWithoutHelloTimesOutAndNonTextHelloFails() async throws {
        let server = try FakeServerKeys(protocolVector("x25519"))
        let fixture = NetworkHTTPFixture { _ in nil }
        defer { fixture.close() }
        let silent = BackendSecureTransport(
            connection: server.connection(fixture), session: fixture.session,
            makeSocket: { FakeV2Server(request: $0, keys: server, hello: nil) }, helloTimeout: .milliseconds(50))
        await #expect(throws: TodexError.self) { _ = try await silent.openWebSocket() }
        let binary = Mutex<FakeV2Server?>(nil)
        let wrongHello = BackendSecureTransport(
            connection: server.connection(fixture), session: fixture.session,
            makeSocket: { request in
                let fake = FakeV2Server(request: request, keys: server, hello: .data(Data("{}".utf8)))
                binary.withLock { $0 = fake }
                return fake
            })
        await #expect(throws: TransportCryptoError.self) { _ = try await wrongHello.openWebSocket() }
        #expect(binary.withLock { $0?.closeCode } == TransportV2.wsCloseCode)
    }
}

// MARK: - Helpers

private func vectors() throws -> JSONValue {
    let url = try #require(Bundle.module.url(forResource: "transport-v2", withExtension: "json", subdirectory: "Fixtures"))
    return try JSONDecoder().decode(JSONValue.self, from: Data(contentsOf: url))
}

private func protocolVector(_ name: String) throws -> JSONValue {
    try #require(vectors()["protocols"].arrayValue.first { $0["protocol"].stringValue == name })
}

/// x25519 from the client secret; ML-KEM by decapsulating the vector
/// ciphertext with the server key (CryptoKit cannot encapsulate deterministically).
private func clientHandshake(_ v: JSONValue, _ part: JSONValue) throws -> TransportClientHandshake {
    let serverPublic = try hex(v["server"]["publicKey"])
    if v["protocol"] == "x25519" {
        return try .x25519(
            serverPublicKey: serverPublic,
            privateKey: .init(rawRepresentation: hex(part["client"]["secretKey"])))
    }
    let server = try MLKEM768.PrivateKey(seedRepresentation: hex(v["server"]["keygenSeed"]), publicKey: nil)
    #expect(server.publicKey.rawRepresentation == serverPublic)
    let ciphertext = try hex(part["clientMaterial"])
    let shared = try server.decapsulate(ciphertext)
    #expect(shared.bytes == (try hex(part["shared"])))
    return TransportClientHandshake(encryption: .mlkem768, clientMaterial: ciphertext, shared: shared)
}

private func wsChannel(_ v: JSONValue, maxFrameBytes: Int = TransportV2.maxWebSocketFrameBytes) throws
    -> TransportWebSocketChannel
{
    let ws = v["ws"]
    return try TransportWebSocketHandshake(
        serverPublicKey: hex(v["server"]["publicKey"]), deviceID: ws["deviceId"].stringValue,
        handshake: clientHandshake(v, ws), clientNonce: hex(ws["clientNonce"]), maxFrameBytes: maxFrameBytes
    ).acceptHello(ws["hello"].stringValue)
}

private func restKeys(_ v: JSONValue) throws -> TransportKeys {
    let rest = v["rest"]
    return try TransportKeySchedule.derive(
        label: TransportV2.restLabel, deviceID: "", serverStaticPublic: hex(v["server"]["publicKey"]),
        handshake: clientHandshake(v, rest), clientNonce: hex(rest["clientNonce"]), serverNonce: Data())
}

private func sha256Hex(_ data: Data) -> String { SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined() }

private func hex(_ value: JSONValue) throws -> Data { try hex(value.stringValue) }

private func hex(_ value: String) throws -> Data {
    let bytes = Array(value.utf8)
    guard bytes.count.isMultiple(of: 2) else { throw TodexError.invalid("odd hex length") }
    return try Data(
        stride(from: 0, to: bytes.count, by: 2).map { index in
            guard let byte = UInt8(String(decoding: bytes[index..<index + 2], as: UTF8.self), radix: 16) else {
                throw TodexError.invalid("bad hex")
            }
            return byte
        })
}

extension SymmetricKey {
    fileprivate var bytes: Data { withUnsafeBytes { Data($0) } }
}

/// URLSession hands URLProtocol either httpBody or a stream; read both.
private func requestBody(_ request: URLRequest) throws -> Data {
    if let body = request.httpBody { return body }
    guard let stream = request.httpBodyStream else { return Data() }
    stream.open()
    defer { stream.close() }
    var data = Data()
    var buffer = [UInt8](repeating: 0, count: 4096)
    while true {
        let count = stream.read(&buffer, maxLength: buffer.count)
        if count < 0 { throw stream.streamError ?? URLError(.cannotDecodeRawData) }
        if count == 0 { break }
        data.append(contentsOf: buffer.prefix(count))
    }
    return data
}

/// Server half of the key agreement, from the vector's static key pair.
private struct FakeServerKeys: Sendable {
    let encryption: EncryptionProtocol
    let publicKey: Data
    private let x25519: Curve25519.KeyAgreement.PrivateKey?
    private let seed: Data?

    init(_ v: JSONValue) throws {
        publicKey = try hex(v["server"]["publicKey"])
        if v["protocol"] == "x25519" {
            encryption = .x25519
            x25519 = try .init(rawRepresentation: hex(v["server"]["secretKey"]))
            seed = nil
        } else {
            encryption = .mlkem768
            x25519 = nil
            seed = try hex(v["server"]["keygenSeed"])
        }
    }

    func handshake(material: Data) throws -> TransportClientHandshake {
        if let x25519 {
            return TransportClientHandshake(
                encryption: .x25519, clientMaterial: material,
                shared: try CryptoEncoding.sharedSecret(privateKey: x25519, publicKey: material))
        }
        let key = try MLKEM768.PrivateKey(seedRepresentation: seed!, publicKey: nil)
        return TransportClientHandshake(encryption: .mlkem768, clientMaterial: material, shared: try key.decapsulate(material))
    }

    func keys(label: String, deviceID: String, material: Data, clientNonce: Data, serverNonce: Data) throws -> TransportKeys {
        TransportKeySchedule.derive(
            label: label, deviceID: deviceID, serverStaticPublic: publicKey, handshake: try handshake(material: material),
            clientNonce: clientNonce, serverNonce: serverNonce)
    }

    func openRequest(_ request: URLRequest) throws -> (TransportInnerRequest, TransportRecordCipher) {
        func header(_ name: String) throws -> String { try #require(request.value(forHTTPHeaderField: name)) }
        #expect(try header("Content-Type") == TransportV2.sealedContentType)
        #expect(try header("x-todex-transport") == "2" && header("x-todex-encryption") == encryption.rawValue)
        let material = try CryptoEncoding.decode(
            header(encryption == .x25519 ? TransportV2.Header.clientKey : TransportV2.Header.kemCiphertext))
        let keys = try keys(
            label: TransportV2.restLabel, deviceID: "", material: material,
            clientNonce: CryptoEncoding.decode(header(TransportV2.Header.requestNonce), count: 32), serverNonce: Data())
        let up = TransportRecordCipher(key: keys.kUp, th: keys.th, direction: TransportV2.directionUp)
        let inner = try TransportInnerRequest.decode(TransportRecordStream.open(requestBody(request), cipher: up))
        return (inner, TransportRecordCipher(key: keys.kDown, th: keys.th, direction: TransportV2.directionDown))
    }

    func reply(_ response: TransportInnerResponse, cipher: TransportRecordCipher) throws -> NetworkHTTPReply {
        NetworkHTTPReply(
            status: 200, data: try TransportRecordStream.seal(response.encoded(), cipher: cipher),
            headers: ["Content-Type": TransportV2.sealedContentType])
    }

    func connection(_ fixture: NetworkHTTPFixture, deviceSecret: String = "") -> BackendConnection {
        var connection = fixture.client(deviceSecret: deviceSecret).connection
        connection.encryption = encryption
        connection.publicKey = CryptoEncoding.encode(publicKey)
        return connection
    }

    func transport(_ fixture: NetworkHTTPFixture, deviceSecret: String = "") -> BackendSecureTransport {
        BackendSecureTransport(
            connection: connection(fixture, deviceSecret: deviceSecret), session: fixture.session,
            makeSocket: { _ in FakeV2Server.unreachable() })
    }
}

/// In-memory `/v2/ws` peer: sends the hello, opens client frames with
/// `k_up`, answers pings and seals pushes with `k_down`.
private final class FakeV2Server: RawWebSocket {
    private struct State {
        var inbound: [WebSocketMessage] = []
        var reader: CheckedContinuation<WebSocketMessage, any Error>?
        var closed = false
        var closeCode: Int?
        var closeReason: String?
        var receivedTypes: [String] = []
        var textFramesAfterHello = 0
        var up: TransportRecordCipher?
        var down: TransportRecordCipher?
    }
    private let state = Mutex(State())
    let query: [String: String]
    let deviceID: String

    static func unreachable() -> FakeV2Server {
        FakeV2Server(query: [:])
    }

    private init(query: [String: String]) {
        self.query = query
        deviceID = ""
    }

    init(request: URLRequest, keys: FakeServerKeys, hello: WebSocketMessage?? = .some(nil)) {
        let items = URLComponents(url: request.url!, resolvingAgainstBaseURL: false)?.queryItems ?? []
        query = Dictionary(items.map { ($0.name, $0.value ?? "") }, uniquingKeysWith: { _, last in last })
        deviceID = query["device_id"] ?? ""
        let serverNonce = TransportBytes.random(32)
        if let material = try? CryptoEncoding.decode(query[keys.encryption == .x25519 ? "client_key" : "ciphertext"] ?? ""),
            let clientNonce = try? CryptoEncoding.decode(query["client_nonce"] ?? "", count: 32),
            let derived = try? keys.keys(
                label: TransportV2.wsLabel, deviceID: deviceID, material: material, clientNonce: clientNonce,
                serverNonce: serverNonce)
        {
            state.withLock {
                $0.up = TransportRecordCipher(key: derived.kUp, th: derived.th, direction: TransportV2.directionUp)
                $0.down = TransportRecordCipher(key: derived.kDown, th: derived.th, direction: TransportV2.directionDown)
            }
        }
        switch hello {
        case .some(.none):
            deliver(.text(#"{"type":"todex.transport.hello","version":2,"serverNonce":"\#(CryptoEncoding.encode(serverNonce))"}"#))
        case .some(.some(let message)): deliver(message)
        case .none: break
        }
    }

    var receivedTypes: [String] { state.withLock { $0.receivedTypes } }
    var textFramesAfterHello: Int { state.withLock { $0.textFramesAfterHello } }
    var closeCode: Int? { state.withLock { $0.closeCode } }
    var closeReason: String? { state.withLock { $0.closeReason } }

    func send(_ message: WebSocketMessage, completion: @escaping @Sendable ((any Error)?) -> Void) {
        do {
            guard case .data(let frame) = message else {
                state.withLock { $0.textFramesAfterHello += 1 }
                completion(nil)
                return
            }
            let text = try state.withLock { state -> String in
                let up = try #require(state.up)
                let plaintext = try up.open(
                    counter: TransportBytes.readU64(frame.prefix(8)), ciphertext: frame.dropFirst(8), final: false)
                return String(decoding: plaintext, as: UTF8.self)
            }
            let value = try JSONDecoder().decode(JSONValue.self, from: Data(text.utf8))
            state.withLock { $0.receivedTypes.append(value["type"].stringValue) }
            completion(nil)
            // Pings answer pong; anything else echoes its payload as the result.
            try push([
                "id": value["id"], "type": "server.result",
                "payload": value["type"] == "server.ping" ? ["pong": true] : value["payload"],
            ])
        } catch { completion(error) }
    }

    func push(_ value: JSONValue) throws {
        let frame = try state.withLock { state -> Data in
            let sealed = try #require(state.down).seal(Data(value.prettyPrinted.utf8), final: false)
            return TransportBytes.u64(sealed.counter) + sealed.ciphertext
        }
        deliver(.data(frame))
    }

    func pushTampered(_ value: JSONValue) {
        let frame = try! state.withLock { state -> Data in
            let sealed = try #require(state.down).seal(Data(value.prettyPrinted.utf8), final: false)
            var frame = TransportBytes.u64(sealed.counter) + sealed.ciphertext
            frame[frame.count - 1] ^= 1
            return frame
        }
        deliver(.data(frame))
    }

    private func deliver(_ message: WebSocketMessage) {
        let reader: CheckedContinuation<WebSocketMessage, any Error>? = state.withLock {
            guard !$0.closed else { return nil }
            if let reader = $0.reader {
                $0.reader = nil
                return reader
            }
            $0.inbound.append(message)
            return nil
        }
        reader?.resume(returning: message)
    }

    func receive() async throws -> WebSocketMessage {
        try await withCheckedThrowingContinuation { continuation in
            let result: Result<WebSocketMessage, any Error>? = state.withLock {
                if !$0.inbound.isEmpty { return .success($0.inbound.removeFirst()) }
                if $0.closed { return .failure(URLError(.networkConnectionLost)) }
                $0.reader = continuation
                return nil
            }
            if let result { continuation.resume(with: result) }
        }
    }

    func close(code: Int, reason: String) {
        let reader = state.withLock {
            $0.closeCode = $0.closeCode ?? code
            $0.closeReason = $0.closeReason ?? reason
            $0.closed = true
            defer { $0.reader = nil }
            return $0.reader
        }
        reader?.resume(throwing: URLError(.networkConnectionLost))
    }

    func cancel() {
        let reader = state.withLock {
            $0.closed = true
            defer { $0.reader = nil }
            return $0.reader
        }
        reader?.resume(throwing: URLError(.cancelled))
    }
}
